// CFS_LIST
export const CFSLIST_GET_REQUESTED = 'CFS_LIST/CFSLIST_GET_REQUESTED';
export const CFSLIST_GET_SUCCEED = 'CFS_LIST/CFSLIST_GET_SUCCEED';
export const CFSLIST_GET_FAILED = 'CFS_LIST/CFSLIST_GET_FAILED';

// CFS_INFO
export const CFSINFO_GET_REQUESTED = 'CFS_INFO/CFSINFO_GET_REQUESTED';
export const CFSINFO_GET_SUCCEED = 'CFS_INFO/CFSINFO_GET_SUCCEED';
export const CFSINFO_GET_FAILED = 'CFS_INFO/CFSINFO_GET_FAILED';
export const CFSINFO_POST_REQUESTED = 'CFS_INFO/CFSINFO_POST_REQUESTED';
export const CFSINFO_POST_SUCCEED = 'CFS_INFO/CFSINFO_POST_SUCCEED';
export const CFSINFO_POST_FAILED = 'CFS_INFO/CFSINFO_POST_FAILED';
export const CFSINFO_PUT_REQUESTED = 'CFS_INFO/CFSINFO_PUT_REQUESTED';
export const CFSINFO_PUT_SUCCEED = 'CFS_INFO/CFSINFO_PUT_SUCCEED';
export const CFSINFO_PUT_FAILED = 'CFS_INFO/CFSINFO_PUT_FAILED';
export const CFSINFO_PATCH_REQUESTED = 'CFS_INFO/CFSINFO_PATCH_REQUESTED';
export const CFSINFO_PATCH_SUCCEED = 'CFS_INFO/CFSINFO_PATCH_SUCCEED';
export const CFSINFO_PATCH_FAILED = 'CFS_INFO/CFSINFO_PATCH_FAILED';

// CFS_LOG
export const CFSLOG_POST_REQUESTED = 'CFS_LOG/CFSLOG_POST_REQUESTED';
export const CFSLOG_POST_SUCCEED = 'CFS_LOG/CFSLOG_POST_SUCCEED';
export const CFSLOG_POST_FAILED = 'CFS_LOG/CFSLOG_POST_FAILED';
export const CFSLOG_GET_REQUESTED = 'CFS_LOG/CFSLOG_GET_REQUESTED';
export const CFSLOG_GET_SUCCEED = 'CFS_LOG/CFSLOG_GET_SUCCEED';
export const CFSLOG_GET_FAILED = 'CFS_LOG/CFSLOG_GET_FAILED';
export const SYSTEM_LOG_TOGGLED = 'CFS_LOG/SYSTEM_LOG_TOGGLED';
export const USER_LOG_TOGGLED = 'CFS_LOG/USER_LOG_TOGGLED';
export const TONE_LOG_TOGGLED = 'CFS_LOG/TONE_LOG_TOGGLED';

// CFS_RELATED
export const CFSRELATED_GET_REQUESTED = 'CFS_RELATED/CFSRELATED_GET_REQUESTED';
export const CFSRELATED_GET_SUCCEED = 'CFS_RELATED/CFSRELATED_GET_SUCCEED';
export const CFSRELATEDT_GET_FAILED = 'CFS_RELATED/CFSRELATEDT_GET_FAILED';

// Counter
export const INCREMENT_REQUESTED = 'Counter/INCREMENT_REQUESTED';
export const INCREMENT_SUCCESS = 'Counter/INCREMENT_SUCCESS';
export const DECREMENT_REQUESTED = 'Counter/DECREMENT_REQUESTED';
export const DECREMENT_SUCCESS = 'Counter/DECREMENT_SUCCESS';
