// itemsByCategory
export const CFS_LIST = 'CFS_LIST';
export const CFS_LIST_FETCHED = 'CFS_LIST_FETCHED';
export const CFS_INFO = 'CFS_INFO';
export const CFS_INFO_FETCHED = 'CFS_INFO_FETCHED';
export const CFS_LOG = 'CFS_LOG';
export const CFS_LOG_FETCHED = 'CFS_LOG_FETCHED';
export const CFS_RELATED = 'CFS_RELATED';
export const CFS_RELATED_FETCHED = 'FETCH_CFS_RELATED_SUCCEEDED';

// counter
export const INCREMENT_REQUESTED = 'counter/INCREMENT_REQUESTED';
export const INCREMENT_SUCCESS = 'counter/INCREMENT_SUCCESS';
export const DECREMENT_REQUESTED = 'counter/DECREMENT_REQUESTED';
export const DECREMENT_SUCCESS = 'counter/DECREMENT_SUCCESS';

// cfsLog
export const POST_CFSLOG_REQUESTED = 'cfsLog/POST_CFSLOG_REQUESTED';
export const POST_CFSLOG_SUCCESS = 'cfsLog/POST_CFSLOG_SUCCESS';
export const POST_CFSLOG_FAILURE = 'cfsLog/POST_CFSLOG_FAILURE';
export const REFRESH_CFSLOG_REQUESTED = 'cfsLog/REFRESH_CFSLOG_REQUESTED';
export const REFRESH_CFSLOG_SUCCESS = 'cfsLog/REFRESH_CFSLOG_SUCCESS';
export const REFRESH_CFSLOG_FAILURE = 'cfsLog/REFRESH_CFSLOG_FAILURE';
export const TOGGLE_SHOW_SYSTEM_LOG = 'cfsLog/TOGGLE_SHOW_SYSTEM_LOG';
export const TOGGLE_SHOW_USER_LOG = 'cfsLog/TOGGLE_SHOW_USER_LOG';
export const TOGGLE_SHOW_TONE_LOG = 'cfsLog/TOGGLE_SHOW_TONE_LOG';

// cfsInfo
export const GET_CFSINFO_REQUESTED = 'cfsInfo/GET_CFSINFO_REQUESTED';
export const GET_CFSINFO_SUCCESS = 'cfsInfo/GET_CFSINFO_SUCCESS';
export const GET_CFSINFO_FAILURE = 'cfsInfo/GET_CFSINFO_FAILURE';
export const POST_CFSINFO_REQUESTED = 'cfsInfo/POST_CFSINFO_REQUESTED';
export const POST_CFSINFO_SUCCESS = 'cfsInfo/POST_CFSINFO_SUCCESS';
export const POST_CFSINFO_FAILURE = 'cfsInfo/POST_CFSINFO_FAILURE';
export const PUT_CFSINFO_REQUESTED = 'cfsInfo/PUT_CFSINFO_REQUESTED';
export const PUT_CFSINFO_SUCCESS = 'cfsInfo/PUT_CFSINFO_SUCCESS';
export const PUT_CFSINFO_FAILURE = 'cfsInfo/PUT_CFSINFO_FAILURE';
export const PATCH_CFSINFO_REQUESTED = 'cfsInfo/PATCH_CFSINFO_REQUESTED';
export const PATCH_CFSINFO_SUCCESS = 'cfsInfo/PATCH_CFSINFO_SUCCESS';
export const PATCH_CFSINFO_FAILURE = 'cfsInfo/PATCH_CFSINFO_FAILURE';
