// counter
export const INCREMENT_REQUESTED = 'counter/INCREMENT_REQUESTED';
export const INCREMENT_SUCCESS = 'counter/INCREMENT_SUCCESS';
export const DECREMENT_REQUESTED = 'counter/DECREMENT_REQUESTED';
export const DECREMENT_SUCCESS = 'counter/DECREMENT_SUCCESS';

// cfslog
export const APPEND_CFSLOG_REQUESTED = 'cfslog/APPEND_CFSLOG_REQUESTED';
export const APPEND_CFSLOG_SUCCESS = 'cfslog/APPEND_CFSLOG_SUCCESS';
export const APPEND_CFSLOG_FAILURE = 'cfslog/APPEND_CFSLOG_FAILURE';
export const REFRESH_CFSLOG_REQUESTED = 'cfslog/REFRESH_CFSLOG_REQUESTED';
export const REFRESH_CFSLOG_SUCCESS = 'cfslog/REFRESH_CFSLOG_SUCCESS';
export const REFRESH_CFSLOG_FAILURE = 'cfslog/REFRESH_CFSLOG_FAILURE';
export const SHOW_CFSLOG_ALL = 'cfslog/SHOW_CFSLOG_ALL';
export const SHOW_CFSLOG_SYSTEMTEXT = 'cfslog/SHOW_CFSLOG_SYSTEMTEXT';
export const SHOW_CFSLOG_USERTEXT = 'cfslog/SHOW_CFSLOG_USERTEXT';
export const SHOW_CFSLOG_TONE = 'cfslog/SHOW_CFSLOG_TONE';

// cfsDetail
export const UPDATE_CFSSTATUS_REQUESTED = 'cfsdetail/UPDATE_CFSSTATUS_REQUESTED';
export const UPDATE_CFSSTATUS_SUCCESS = 'cfsdetail/UPDATE_CFSSTATUS_SUCCESS';
export const UPDATE_CFSSTATUS_FAILURE = 'cfsdetail/UPDATE_CFSSTATUS_FAILURE';
